$(function() {
    $(".itemA").click(function(){
        $(".modalA").addClass("modal-open")
    })
    $(".close-btn").click(function(){
        $(".modalA").removeClass("modal-open")
    })
    $(".itemB").click(function(){
        $(".modalB").addClass("modal-open")
    })
    $(".close-btn").click(function(){
        $(".modalB").removeClass("modal-open")
    })
    $(".itemC").click(function(){
        $(".modalC").addClass("modal-open")
    })
    $(".close-btn").click(function(){
        $(".modalC").removeClass("modal-open")
    })
    $(".itemD").click(function(){
        $(".modalD").addClass("modal-open")
    })
    $(".close-btn").click(function(){
        $(".modalD").removeClass("modal-open")
    })
    $(".itemE").click(function(){
        $(".modalE").addClass("modal-open")
    })
    $(".close-btn").click(function(){
        $(".modalE").removeClass("modal-open")
    })
    $(".itemF").click(function(){
        $(".modalF").addClass("modal-open")
    })
    $(".close-btn").click(function(){
        $(".modalF").removeClass("modal-open")
    })
    });